### ISSUE TITLE
err or not

### ISSUE THREAD

**Issue by DenDx** [splorp/wordpress-comment-blacklist#10]
The list includes in, is, and it.  Shouldn't flag these words should it?

**Comment by splorp** [comment]
Actually, the list doesn’t include ‘in’, ‘is’, or ‘it’ … at least not the English versions.

Those terms contain the character ‘і’ (Unicode 0456), which looks amazingly similar to the lowercase ‘i’.

It is a common practice of spammers to replace ASCII characters with visually similar Unicode characters to bypass language or spelling-based filters. Words containing those characters still appear correct to the user.
