### ISSUE TITLE
Removal of common indexes

### ISSUE THREAD

**Issue by jvoisin** [splorp/wordpress-comment-blacklist#11]
What about removing `/index.php`, `/index.aspx`, … from the blacklist?

**Comment by splorp** [comment]
Yeah, I agree that `/index.*` terms should probably be removed … they’re a bit too general.

Are there any other “common index” names you would like me to consider? I’m not currently including `/default.*` (used on some older Mac-based servers) as a term.

**Comment by splorp** [comment]
Ok, I’ve decided to remove the following common filenames from the blacklist:

```
/home.
/index.asp
/index.php
```

Let me know if there are any other index filenames that should be considered.
