### ISSUE TITLE
Contact Form 7 now marks most submissions as spam

### ISSUE THREAD

**Issue by bradydan** [splorp/wordpress-comment-blacklist#12]
This has been working great for a while, across a number of sites. Recently, all WordPress sites using:
1. Contact Form 7
2. Comment Blacklist Manager plugin
3. This source of blacklist entries

Have been marking most form submissions as spam, and therefore not sending.

If I empty the blacklist, it works fine.

I haven't investigated any further than that yet

**Comment by bradydan** [comment]
FWIW I think "youre" should be removed. It's an easy typo for a genuine user to make

**Comment by bradydan** [comment]
As an experiment, I wiped the blacklist then ran the manual update to repopulate the blacklist. Fails again:

> Failed to send your message. Please try later or contact the administrator by another method.

We have 'WP reCaptcha Integration' and 'honeypot' on this form too

**Comment by splorp** [comment]
There are far too many variables here to begin determine what the source of the issue might be. My guess is that one of other plugins affecting the submissions is choking (or improperly parsing) some string in the blacklist. The fact that the issue disappears when the blacklist is cleared is a good indicator of this.

One thing to try is whittling down the blacklist, adding chunks of it back into the mix, to pinpoint where the failure might be occurring.

Also, have you tried disabling [Contact Form 7](https://wordpress.org/plugins/contact-form-7/), [Honeypot](https://wordpress.org/plugins/contact-form-7-honeypot/) or [WP reCaptcha Integration](https://wordpress.org/plugins/wp-recaptcha-integration/) independently to see if one or more of those plugins is at fault?

**Comment by splorp** [comment]
> FWIW I think "youre" should be removed. It's an easy typo for a genuine user to make

Perhaps. But it’s also a very common, deliberate misspelling used by spammers.

Let me think about that one.

**Comment by bradydan** [comment]
> Perhaps. But it’s also a very common, deliberate misspelling used by spammers.

My rule would be: if genuine users are likely to type it at some point, it shouldn't be on the list 

I thought the same about the blacklist trimming and plugin conflicts. Just didn't have time to do that. If I get time I will try.

**Comment by splorp** [comment]
> My rule would be: if genuine users are likely to type it at some point, it shouldn't be on the list

Good point. I’ll remove it from the next release.

> I thought the same about the blacklist trimming and plugin conflicts.

I may be able to set up a test environment for this. Would you be able to post an example of the type of comment you have been posting?

**Comment by bradydan** [comment]
Thanks. 

Here's an example

your-subject: ` A test from eth website conatct form`
your-message: 
```
Have you received this message?

Thanks

Dan
```

There are a couple of typos in the subject, but neither are in the blacklist

**Comment by bradydan** [comment]
ps this exact message failed with the blacklist populated (fresh manual update) and was successful when the blacklist was empty

**Comment by splorp** [comment]
Even though my WordPress install doesn’t have the “subject” field for comments (I’m assuming that is part of [Contact Form 7](https://wordpress.org/plugins/contact-form-7/), I tested this exact text and the comment went through. What email address and URL are you using when you post?

The next step is to install those other plugins on my test site and see what happens.

**Comment by splorp** [comment]
To duplicate my set up, can you send me a copy of your contact form settings, including the honeypot and recaptcha code? Thanks.

**Comment by splorp** [comment]
According to the plugin’s support page, there appear to be plenty of issues with WP-reCaptcha and recent versions of WordPress.

https://wordpress.org/support/plugin/wp-recaptcha

My guess is that it’s a combination of something contained in the blacklist and an incompatibility between WP-reCaptcha and the WordPress core.

**Comment by bradydan** [comment]
I'm still having issues with this blacklist and Contact Form 7.  The issue goes away when I clear the blacklist, so to me at least that points to a match.

It would be very useful for debugging if the reason (eg specific keyword match) was logged when a comment was marked as spam.

Looking through the blacklist, I see many terms that could be false positives. Whilst these *could* be spammers, IMO there are also reasons why a genuine user/enquirer might use these terms:

```
my blog
my blog:
my fashion
my hermes
my homepag
my myspace
my online
my page:
my site;
my site:
my sitte
my ssite
my web:
my weblog
my weblog:
my webpage
my webpage:
my website
my website:
news/article
newsarticle
newwebsite
/contact-
onlyway
ontheir
per-week
```

This is not an exhaustive list

**Comment by splorp** [comment]
I cannot find any specific section (terms, words, phrases, or otherwise) in the blacklist which is causing the Contact Form 7 failure. In my opinion, it is a programmatic issue with Contact Form 7 related to parsing a relativity large blacklist.

Have you tried posting a question about this issue to the [Contact Form 7 support forum](https://wordpress.org/support/plugin/contact-form-7)? This may be something that they need to investigate independently.

As for the terms that could potentially result in false positives, I’ll definitely take a look at these again. You’re right, some of these are probably common enough to warrant removal from the blacklist.

**Comment by splorp** [comment]
Hi @bradydan … I have reviewed your list of [potential false positive terms](https://github.com/splorp/wordpress-comment-blacklist/issues/12#issuecomment-288345672) above and removed several of them (along with a few others) from the blacklist. I’m going to closely monitor how this affects the flagging of comments across several of my sites. If I noticed an increase in missed spam, I will likely add them back.

**Comment by bradydan** [comment]
Thanks @splorp 

I guess it depends where you draw the line. For me, and for my clients, it is far worse to miss genuine enquiries, than to allow a very occasional spam message to appear. But I am using this in the context of contact form 7 enquiries, where a false positive can mean a lost sale.

If you find an increase in spam messages, rather than re-adding the recently removed phrases, I suggest finding alternative patterns that are less likely to be used by genuine users.

**Comment by bradydan** [comment]
I suppose another option is to have a separate list which is less strict, and allow web admins to choose in the admin screens

**Comment by splorp** [comment]
I completely understand your concern.

Separate lists are an interesting idea, but they’re not something that I plan on maintaining. The reason I provided the blacklist as an open source project is so people like yourself can fork the master list and create your own custom or simplified set of terms, while still grabbing relevant updates going forward.

When I have a bit more time, I’ll try to do some more testing with Contact Form 7. But as I mentioned above, it seems like more of a compatibility issue with their code, than with my static list of terms.

**Comment by bradydan** [comment]
Thanks, I did consider forking it, and may do just that. I'll also raise the issue with CF7

Thanks for your help

**Comment by splorp** [comment]
Please let me know how that goes.

Happy to work with them on a solution, if it’s something that can be mitigated.

**Comment by bradydan** [comment]
FYI I've raised this on the CF7 support here: https://wordpress.org/support/topic/conflict-with-very-long-comment-blacklist/

**Comment by splorp** [comment]
Hey Dan. I’ve added a little bit of background to that support thread regarding my investigation into the issue.

**Comment by DrDave89** [comment]
I have the same problem with C7 but do not use a blacklist plug-in.  I've made sure the comments blacklist in Settings>Discussion is empty.
The settings in CF7 are correct - uses existing email address on same server.  Tried using Easy WP SMTP plugin and any other tweaks mentioned on help sites - I've disabled Aksimet...
Any ideas before I ditch CF7?

**Comment by splorp** [comment]
Hmmm … it’s interesting that you’re experiencing an similar issue without the blacklist components.

I don’t use CF7 on any of my sites, so I really don’t have any additional suggestions regarding the problem. Also, since the author of CF7 never responded to the support thread posted two nearly years ago, it seems that they don‘t think it’s a problem worth investigating.

I wish I had a solution for you.

**Comment by DrDave89** [comment]
Having gone through umpteen fixes from various forums, no. 2 on here worked.  https://wordpress.org/support/topic/3-spam-fixes-contact-form-7-v5-1/

**Comment by splorp** [comment]
Thanks for the pointer.

**Comment by splorp** [comment]
The above link is dead. Here’s an archived version:

https://web.archive.org/web/20190308185254/https://wordpress.org/support/topic/3-spam-fixes-contact-form-7-v5-1/
