### ISSUE TITLE
New term suggestions

### ISSUE THREAD

**Issue by gummylick** [splorp/wordpress-comment-blacklist#13]
I just cleaned out my spam, here's some suggestions:

gginza
louisvuitton
calvinklein
kakaku
rolex
wtobrand
gowatchs
eevance
brandiwc
bestevance
ooobag
ooobrand
ooowatch
laferradura

**Comment by splorp** [comment]
Thanks for the suggested additions.

I will add most of these to the blacklist (along with their variations), with the exception of a few …

Terms such as `louisvuitton`, `calvinklein`, `laferradura`, `kakaku`, and `rolex` are common brand names used in legitimate website addresses. Including them in the blacklist would filter legitimate websites such as [rolex.com](http://rolex.com/) or [calvinklein.ca](http://calvinklein.ca/).

If these terms appear with other “spammy” words or phrases, then I would include them. Is it possible to provide a sample of the entire comment text where some of these terms appeared?

**Comment by splorp** [comment]
New terms added per commit: 622e924a2bf29328abcee45b7aeb59fca5439cef
