### ISSUE TITLE
HTTP ERROR 500 when trying to save

### ISSUE THREAD

**Issue by zurdo1123** [splorp/wordpress-comment-blacklist#21]
I'm experiencing some HTTP ERROR 500 when i try to save my changes. I've been using the blacklist in other wordpress installations and this is the first time that these happen. Could you give me some recommendations of why this may be happening. Thank you very much.

**Comment by splorp** [comment]
The 500 code indicates an “Internal Server Error” which could mean many things.

Is the WordPress installation where you are seeing this error on the same server (or web host) as the other installations which are working? If it’s a different server or host, then it could be something to do with the server configuration for timeouts or the size of data allowed to be submitted in a form (which is how the WordPress settings are handled).

For example, Media Temple lists one of the possible causes of a 500 error as PHP code timing out or taking too long to execute.

[Media Temple: Why am I getting a 500 Internal Server Error message?
](https://mediatemple.net/community/products/dv/204644990/why-am-i-getting-a-500-internal-server-error-message)

Where is this WordPress installation hosted?

**Comment by zurdo1123** [comment]
Hello, sorry for the late response. Thank you for your support. It was a simple fix, as you commented, the error was due to PHP code timing out. So, i just increased the PHP memory to 256M. And that was it. So, thank you again for the support and for compiling this list.

**Comment by splorp** [comment]
Happy to hear that you solved the issue.
