### ISSUE TITLE
Not Acceptable! Mod_Security

### ISSUE THREAD

**Issue by acnuzzi** [splorp/wordpress-comment-blacklist#22]
Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

Hey.. I was wondering why i would receive this error.. when I copy just a few they get punched into my blacklist on wordpress just fine... But when I "copy all" and paste, this message pops up.. Would you have an idea why? Apparently, I can go in and change Mod_Security.. From what i read online.. If you  know if there are some key words causing this issue, or maybe the paste all at once... it would be great to know.. Thanks for the help.. NOTE: I can paste all but when I go to save I receive this message.

**Comment by splorp** [comment]
I haven’t heard of Mod_Security before, so I need to do some research before I can answer.

Is this the application you’re referring to?

https://modsecurity.org/

**Comment by acnuzzi** [comment]
You know I think so?? But i'm not sure.. I was able to copy it fine and put it into my blacklist.. Then when I saved I would get this kicked back to me.. I was hoping you saw this before.. lol

**Comment by acnuzzi** [comment]
Ok.. So I had some more time to figure this out.. This is what I found.. Just FYI for anyone who falls to this same issue.. I put the whole thing in excel.. I then cut in half and then cut in half... ETC.. So I finally got the answer  "com/ftp" was giving me this error.. I did not know why.. until I passed that same "com/ftp" into this thread.. This is what I got.. See below.. 

I only got this when I took it from excel.. You do not see the "--" when you view it in excel. You only see it when you copy from excel to this page.. If you copy from your text.. You only get "com/ftp".. Again you do not see "--" So once I paste what you see below into this page and deleted the "--" I plugged it back into at the bottom..... Drum roooolll.. It worked.. For some reason this "--" is hidden within your .txt... I don't know why. or how this happened.. But it works now with no issue.. I hope this made sense.. but if you want to see the same thing - copy your entire text into excel --- then copy only that box "10537" from excel ---  place in here and you should see what I got.. I am using excel 2007 as well.. This was really odd. But problem solved.. 


This is what I got when I copied from excel... The Hidden "--"

com/ftp
--

**Comment by acnuzzi** [comment]
com/ftp
--


77777

**Comment by acnuzzi** [comment]
Boy this took a while.. Thanks for the great list btw.. I'm not sure if this helps you or not.. I'm not sure if anyone else ran into this problem.. Either Here you go folks..

**Comment by splorp** [comment]
I’m not sure where that invisible double dash/hyphen is coming from.

Those invisable characters do not exist locally in my master blacklist.txt file or in the raw text file downloaded directly from GitHub.

https://raw.githubusercontent.com/splorp/wordpress-comment-blacklist/master/blacklist.txt

How exactly are you copying and pasting the text from the source file into WordPress (or Excel)? Did you download the .zip archive and grab it from there?

https://github.com/splorp/wordpress-comment-blacklist/archive/master.zip

This is a very curious problem. If I can duplicate it on end end of things, I’ll definitely mention it in the documentation.

**Comment by splorp** [comment]
I’m convinced that the _invisible double dash/hyphen_ issue is stemming from the use of Excel to view or edit the blacklist. Excel can take a plain text file and try to parse strings that it reads as formatting or portions of formulas. There are lot of random-looking strings found in the blacklist which may be causing Excel to burp on the content.

I would suggest that you use a text editor (and not a word processor) to view and manipulate the blacklist.

**Comment by codeclinic** [comment]
Microsoft products are notorious for adding hidden code when copy/pasted into other applications. You should always paste content into notepad to remove the hidden markup and then copy that and past to the final destination, to be safe.
