### ISSUE TITLE
German Language Spam

### ISSUE THREAD

**Issue by deebz** [splorp/wordpress-comment-blacklist#23]
Recently recieved a couple of get rich via bit coin spam comments written in German making it through the filter.

Select words/terms:
schnell
BTC pro Woche
So verdienen Sie

**Comment by splorp** [comment]
Thanks for the suggestions.

I wouldn’t add _schnell_ to the list on its own, as it simply means _fast_. Perhaps combined with another word or two for context, then it would be a suitable addition.

However, both _BTC pro Woche_ (or simply _BTC pro_) and _So verdienen Sie_ are good phrases to add.

Would it be possible to post the entire comments (including links, email address, commenter names, etc.)?

**Comment by deebz** [comment]
Hi,

Unfortunately I don't have the comments anymore as I deleted them. If I get a re-occurance I will post again. I suspect the fact that the german comments appeared was due to a blog post featuring german words.

**Comment by splorp** [comment]
I have added the following terms to the blacklist in commit 9dd9100:

btc pro
btc-pro
btcpro
so verdienen sie

And feel free to post additional German comment text, if this happens in the future.
