### ISSUE TITLE
New terms from spam email

### ISSUE THREAD

**Issue by BinaryMoon** [splorp/wordpress-comment-blacklist#30]
Hi - I got a domain spam email as seen below. Not sure what phrases you would add to this but it seems like there's a few potentials.

```
Expiration message of your binarymoon.co.uk

EXPIRATION NOTIFICATION

CLICK HERE FOR SECURE ONLINE PAYMENT: http://domainworldset.com/?n=binarymoon.co.uk&r=a&t=1601071266&p=v1

This purchase expiration notification binarymoon.co.uk advises you about the submission expiration of domain binarymoon.co.uk for your e-book submission.
The information in this purchase expiration notification binarymoon.co.uk may contains CONFIDENTIAL AND/OR LEGALLY PRIVILEGED INFORMATION from the processing department from the processing department to purchase our e-book submission. NON-COMPLETION of your submission by the given expiration date may result in CANCELLATION of the purchase.

CLICK HERE FOR SECURE ONLINE PAYMENT: http://domainworldset.com/?n=binarymoon.co.uk&r=a&t=1601071266&p=v1

ACT IMMEDIATELY. The submission notification binarymoon.co.uk for your e-book will EXPIRE WITHIN 2 DAYS after reception of this email

This notification is intended only for the use of the individual(s) having received this message.

PLEASE CLICK ON SECURE ONLINE PAYMENT TO COMPLETE YOUR PAYMENT

SECURE ONLINE PAYMENT: http://domainworldset.com/?n=binarymoon.co.uk&r=a&t=1601071266&p=v1

Non-completion of your submission by given expiration date may result in cancellation.

All online services will be restored automatically upon confirmation of payment. Delivery will be completed within 24 hours.

CLICK UNDERNEATH FOR IMMEDIATE PAYMENT:

SECURE ONLINE PAYMENT: http://domainworldset.com/?n=binarymoon.co.uk&r=a&t=1601071266&p=v1
```

**Comment by BinaryMoon** [comment]
BTW - also wanted to say thanks a lot for making and maintaining this list. I'm using it my plugin Toolbelt:
https://wordpress.org/plugins/wp-toolbelt/ and it's so effective. Only a few false positives, and no third party servers needed :)

**Comment by splorp** [comment]
Thanks for passing this along.

I can immediately pull out a few obvious terms such as **“CLICK UNDERNEATH”** and **“CLICK ON SECURE”** …

Was this an email or something left as a comment on a post? Just curious.

Also, I’d appreciate knowing about any false positives you come across. Analyzing false positives will help make the blacklist better in the long run.

**Comment by BinaryMoon** [comment]
Thanks! 👍 

This was an email from a contact form, but I use your list to check for spam in the contact form and comments.

I was wondering about **EXPIRATION NOTIFICATION**, **SECURE ONLINE PAYMENT**, **ACT IMMEDIATELY,** and **domainworldset.com** (do you add domain names?)

I'll definitely send you more of them if that would help. I could do it as pull requests if you like but I wasn't sure how you manage that sort of thing or if there are any rules or guidelines I should follow?

**Comment by BinaryMoon** [comment]
Todays spam comment:

```this is awesome informative posting...

"<a>woman wine expert in usa</a>"```

**Comment by splorp** [comment]
> I was wondering about EXPIRATION NOTIFICATION, SECURE ONLINE PAYMENT, ACT IMMEDIATELY, and domainworldset.com (do you add domain names?)

The only phrase that I might consider adding would be variations of the domain name, such as:

- domainworld
- domain-world

I rarely add domain names themselves, other that known link shorteners. Those other phrases, although certainly spammy-sounding, could be used legitimately in comments or posts.

> I could do it as pull requests if you like but I wasn't sure how you manage that sort of thing or if there are any rules or guidelines I should follow?

I’m not too strict about pull requests. Just add the new terms and makes sure everything is sorted alphabetically. I’ll review and often add more variations if required.

> `"<a>woman wine expert in usa</a>"`
>
> I guess `<a>` could be added?

Interestingly enough, `<a>` is already in the blacklist as a term … it appears that I need to do some additional testing, since that one slipped through your system. I know that HTML tag attributes (such as `href=`, `title=`, and so on) are ignored when WordPress processes comment content, but it may be ignoring the element tags as well.

**Comment by BinaryMoon** [comment]
Thanks for the info. I'll see if I can do a pull request next time then :)
