### ISSUE TITLE
Add Gravity Forms Blocklist to Read Me

### ISSUE THREAD

**Issue by splorp** [splorp/wordpress-comment-blacklist#31]
Add a mention about [Gravity Forms Blocklist](https://gravitywiz.com/documentation/gravity-forms-blocklist/) to a new section of the read me, perhaps something like “Plugins that utilize the Comment Blocklist”.

Additional reference:
https://tourkick.com/advice-tips-howto/block-gravity-forms-spam-gravity-perks-disallowed-keywords/

Hat tip to @cliffordp for the information.

**Comment by cliffordp** [comment]
FYI: renamed to 'blocklist'
https://gravitywiz.com/documentation/gravity-forms-blocklist/

**Comment by splorp** [comment]
Upon closer investigation, Gravity Forms does not directly support automated blocklist updates. It requires the use of one of the third-party plugins as [mentioned in the read me](https://github.com/splorp/wordpress-comment-blacklist#how-do-i-use-it).

**Comment by cliffordp** [comment]
I'm not following why this was closed without any updating.

Basically, in addition to needing Gravity Forms (of course) and [Comment Blacklist Updater](https://wordpress.org/plugins/comment-blacklist-updater/) (one of the third-party ones your README already mentions), you'll need [Gravity Forms Blocklist from Gravity Perks](https://gravitywiz.com/documentation/gravity-forms-blocklist/)

Beyond that simplicity, end-user setup instructions are here: https://tourkick.com/advice-tips-howto/block-gravity-forms-spam-gravity-perks-disallowed-keywords/

**Comment by splorp** [comment]
As stated, I closed the issue because Gravity Forms Blocklist does not directly update the Disallowed Comment Keys field, but requires the use of one of the plugins already listed in the read me.

I thought about this again and I’ll look at adding another section to the read me mentioning plugins that utilize the Disallowed Comment Keys field, which Gravity Forms Blocklist certainly falls into.

**Comment by splorp** [comment]
This issue has been resolved per commit 88ab507

**Comment by cliffordp** [comment]
Very nice. ty.
