### ISSUE TITLE
Remove duplicate items from "Local Blacklist" if also in "Disallowed Comment Keys"

### ISSUE THREAD

**Issue by cliffordp** [splorp/wordpress-comment-blacklist#32]
If I add items to "Local Blacklist" that later end up in "Disallowed Comment Keys", such as via a pull request that eventually gets merged, I want to remove all those duplicates.

I was thinking upon each save to run de-dup, and personally I'd prefer that, but I could see some people not. So either do it that way but give an option/filter to disable automatic -- and/or add a button to run it manually.

Doing _only_ a de-dup button is probably the safest way to implement it and keep everyone happy (no surprises on removing without asking due to automatic plugin update).

**Comment by splorp** [comment]
This request definitely brings up a good point regarding overlapping terms in the two fields.

However, it’s a feature request for one of the blacklist/comment key management plugins, not my list of terms. The blacklist itself is just a text file, so I obviously can’t add any programmatic deduplication features to it.

I would suggest that you open an issue with whatever plugin you’re using to update your blacklist/comment keys.

**Comment by cliffordp** [comment]
doh. you're right. tyvm for the thoughtful reply.

https://wordpress.org/support/topic/remove-duplicate-items-from-local-blacklist/
