### ISSUE TITLE
New spam email

### ISSUE THREAD

**Issue by BinaryMoon** [splorp/wordpress-comment-blacklist#33]
Hi - I've had 2 very similar emails come through my contact form which uses the blacklist.

I wonder about adding _TERMINATION of your domain_ and maybe _PAYMENT WITHIN 24 HOURS_?

> YOUR IMMEDIATE ATTENTION TO THIS MESSAGE IS ABSOLUTELY NECESSARY!
> 
> YOUR DOMAIN binarymoon.blog WILL BE TERMINATED WITHIN 24 HOURS
> 
> We have not received your payment for the renewal of your domain binarymoon.blog
> 
> We have made several attempts to reach you by phone, to inform you regarding the TERMINATION of your domain binarymoon.blog
> 
> CLICK HERE FOR SECURE ONLINE PAYMENT: http://yourdomainboth.xyz/?n=binarymoon.blog&r=a&t=1607907113&p=v1
> 
> IF WE DO NOT RECEIVE YOUR PAYMENT WITHIN 24 HOURS, YOUR DOMAIN binarymoon.blog WILL BE TERMINATED
> 
> CLICK HERE FOR SECURE ONLINE PAYMENT: http://yourdomainboth.xyz/?n=binarymoon.blog&r=a&t=1607907113&p=v1
> 
> ACT IMMEDIATELY.
> 
> The submission notification binarymoon.blog will EXPIRE WITHIN 24 HOURS after reception of this email

**Comment by splorp** [comment]
Thanks for posting this.

I’ll parse through the text and see what phrases I can pull out of it.

Cheers!

g.

**Comment by splorp** [comment]
I have added a few new phrases from the text and will push the changes shortly.

I’m confused as to why the “CLICK HERE” line wasn’t caught. I have had “click here” (albeit the lowercase version) in the list for a very long time. The WordPress comment filtering is not supposed to be case sensitive.

Odd.

**Comment by BinaryMoon** [comment]
Thanks for taking a look and adding some extra keywords. That's interesting that "click here" wasn't picked up. I'll have a look at that, see if I can test this message locally and see what has happened.

**Comment by BinaryMoon** [comment]
I'm glad you pointed that out now. I checked and it seems the option key I was filtering to add in your word list had changed from `option_blacklist_keys` to `option_disallowed_keys` and I didn't realise.

I've updated the plugin, and created a simple method for testing the filter function to ensure it works as I expect.

**Comment by splorp** [comment]
I’ve noticed a couple of plugin developers handling the change this way:

https://github.com/pluginkollektiv/blacklist-updater/commit/2ec5be18c78c04e7ec5d865db0f0cfaf44c2ff13

**Comment by BinaryMoon** [comment]
Interesting - thanks!
