### ISSUE TITLE
Blacklisted term causing false positives

### ISSUE THREAD

**Issue by GaryWLewis** [splorp/wordpress-comment-blacklist#34]
The blacklisted word "cialis" is embedded within the word "specialist" which causes a false positive on medical and educational websites (among others).

**Comment by splorp** [comment]
Good catch, Gary.

I’ll update the list by removing “cialis” specifically and then adding a handful of more specific “cialis-related” terms.

Stand by.

**Comment by splorp** [comment]
This issue has been fixed in commit commit ab010aea0873cfef78bcde1f38875fa19df2e1b9
