### ISSUE TITLE
New spam came through today

### ISSUE THREAD

**Issue by salacpavel** [splorp/wordpress-comment-blacklist#35]
This is what I got in inbox today:

Text To Speech In 3 Clicks - Real sounding human voices!. For a free demo. Write a reply here: katesepage@gmail.com

**Comment by splorp** [comment]
Thanks for the information.

I have added a couple of phrases from the text you provided to the blacklist and they will be available as soon as I push a fresh commit this week.

**Comment by splorp** [comment]
The following terms were added in commit 65f1967 to address this issue.

+ s!.
+ write a reply here
