### ISSUE TITLE
New spam came through - 03.02.2021

### ISSUE THREAD

**Issue by salacpavel** [splorp/wordpress-comment-blacklist#36]
text follows:

From: Antonio Meaux <antonio@stardatagroup.com>
Subject: StarDataGroup.com Shutting Down

Message Body:
It is with sad regret to inform you StarDataGroup.com is shutting down.

Fire sale till the 7th of Feb.

Any group of databases listed below is $49 or $149 for all 16 databases in this one time offer.
You can purchase it at www.StarDataGroup.com and view samples.

- LinkedIn Database
 43,535,433 LinkedIn Records

- USA B2B Companies Database
 28,147,835 Companies

- Forex
 Forex South Africa 113,550 Forex Traders
 Forex Australia 135,696 Forex Traders
 Forex UK 779,674 Forex Traders

- UK Companies Database
 521,303 Companies

- German Databases
 German Companies Database: 2,209,191 Companies
 German Executives Database: 985,048 Executives

- Australian Companies Database
 1,806,596 Companies

- UAE Companies Database
 950,652 Companies

- Affiliate Marketers Database
 494,909 records

- South African Databases
 B2B Companies Database: 1,462,227 Companies
 Directors Database: 758,834 Directors
 Healthcare Database: 376,599 Medical Professionals
 Wholesalers Database: 106,932 Wholesalers
 Real Estate Agent Database: 257,980 Estate Agents
 Forex South Africa: 113,550 Forex Traders

Visit www.stardatagroup.com or contact us with any queries.

Kind Regards,
StarDataGroup.com

-- 
This e-mail was sent from a contact form on Centuriontech.eu (http://centuriontech.eu)

**Comment by splorp** [comment]
@salacpavel Thanks for posting this text.

I’ll work on integrating some of the keywords and phrases from this message into an update this weekend.

Cheers!

**Comment by splorp** [comment]
The following terms were added in commit 540fc6f to address this issue.

* affiliate market
* affiliate-market
* affiliatemarket
* forex north
* forex-north
* forex south
* forex-south
* forex trade
* forex-trade
* forextrade
