### ISSUE TITLE
New spam — 10-Feb-2021

### ISSUE THREAD

**Issue by salacpavel** [splorp/wordpress-comment-blacklist#37]
From: Dawn Frasure <dawn@centtip.xyz>
Subject: Invite Bloggers and Webmasters to Fill Out Our Paid Survey

Message Body:
Invite Bloggers and Webmasters to Fill out Paid Surveys

I'm Dawn from Centtip. 

We are working with Inboxdollars to provide bloggers another opportunity to  earn cash.

After joining Inboxdollars, you will be able to get rewards by sharing your opinions online.

Paid surveys have been prepared for you: https://www.centtip.xyz/getcash

Regards,

Dawn Frasure

**Comment by splorp** [comment]
Hey @salacpavel …

Are these spam messages coming through email or your WordPress comment system?

They seem to be formatted like email messages.

**Comment by splorp** [comment]
Regardless of the source, I’ve added the following terms based on this issue.

- getcash
- get-cash
- inboxdollar
- inbox-dollar
- inbox dollar
- inboxcash
- inbox-cash
- inbox cash
