### ISSUE TITLE
phone case spam examples

### ISSUE THREAD

**Issue by BinaryMoon** [splorp/wordpress-comment-blacklist#39]
Hi - I have had about 80 spam messages get through all following the same pattern. I have now blocked the email address since they all use the same one for some reason, but I imagine they will realise using the same one is a silly idea and change at some stage.

<img width="824" alt="Screenshot 2021-08-08 at 22 51 24" src="https://user-images.githubusercontent.com/1004130/128646775-67fe1a8b-e0c7-482b-b204-05867d384a2e.png">

The text does vary a bit (for different products) but there's definitely patterns. I've pasted some of the common messages below:

> Motorola Moto E7 Power Case Cover & Accessories – Oz Cheap Deals
> Motorola Moto E7 Power Case Cover Accessories Screen Protector, Shockproof Clear Case, Wallet Leather Flip Case, Car Mount Holder, Cables & Adapter Sale.

> Motorola Moto G10 Case Cover & Accessories For Sale – Oz Cheap Deals
> 100% Brand New, High-quality Of Motorola Moto G10 Shockproof Case
> Motorola Moto G10 Carbon Fiber is designed for an active lifestyle, you can continue to use your device without removing it from the case.

> Nokia 1.4 Case Cover Screen Protector Accessories Sale | OzCheapDeals
> Nokia 1.4 Case Cover Screen Protector Accessories , Shockproof Clear Gel Case, Wallet Leather Case, Car Charger, Car Mount Holder, Cables & Adapter.

I have also excluded the urls since they were pointing to the spam domain. You can see it in the screenshot above.

**Comment by splorp** [comment]
I think that the best trap here would be for something that captures phrase like:

`cheapdeals`
`cheap-deals`
`cheap deals`

Thanks for passing this along.

**Comment by splorp** [comment]
@BinaryMoon I forget to mention that these terms were added in commit b6f11d6 back on August 14th.

**Comment by splorp** [comment]
You betcha!
