### ISSUE TITLE
This one bypassed the list

### ISSUE THREAD

**Issue by worldsdream** [splorp/wordpress-comment-blacklist#40]
Great list but this one came through:

gaibanda

There is also a couple of comments with phone numbers only. For example:

01961089455

How do you block that one?

**Comment by splorp** [comment]
Is it possible for you to post the entire contents of the comment, including the IP, email, and URL that was submitted? (Which ever of those are available, anyway.) Having a bit more context of who submitted the spam might help create keywords for the blocklist.

**Comment by worldsdream** [comment]
@splorp i already deleted these messages. My bad. The next time I will put all these informations when I create a new issue.
