### ISSUE TITLE
Spam messages

### ISSUE THREAD

**Issue by worldsdream** [splorp/wordpress-comment-blacklist#41]
The backlist.txt file blocks a lot of spam messages. Unfortunately, these two messages came through today:

![firefox_FTsFLJgUhw](https://user-images.githubusercontent.com/12443285/131318690-5db58e5f-3d07-4bd0-b8f8-a7164d50a0e6.png)

**Comment by splorp** [comment]
Thanks for passing these along. There are a few phrases for the blocklist that can be picked out of these examples.

To make it easier for me to add terms in the future, please copy a paste the actual text when opening an issue. Thanks!

**Comment by splorp** [comment]
Terms based on this issue have been added per commit 9e08c7d

**Comment by worldsdream** [comment]
I will copy paste and include screenshots the next time.

You’re welcome and thanks for pushing the changes!

**Comment by splorp** [comment]
You’re welcome!
