### ISSUE TITLE
New spam — 02-Sep-2021

### ISSUE THREAD

**Issue by worldsdream** [splorp/wordpress-comment-blacklist#42]
This one passed in the comments:

Rodneyjet
reduslim@gmail.com
13.233.174.55

[reduslim trovaprezzi](https://reduslim.health/)
Rodneyjet

**Comment by splorp** [comment]
Thanks for the submission.

It looks like the phrase _“trovaprezzi”_ is Italian for _“find prices”_, so I’ll definitely add that to the blocklist. The other elements are a bit too generic to do anything with.

**Comment by splorp** [comment]
Thanks again for these.

I have added new terms per commit 9e08c7d
