### ISSUE TITLE
t-online mails are all marked as spam

### ISSUE THREAD

**Issue by vielhuber** [splorp/wordpress-comment-blacklist#44]
The email provider [t-online.de](https://www.t-online.de/) is widespread e.g. in Germany.

All form requests (checked in this case with Contact Form 7 against https://raw.githubusercontent.com/splorp/wordpress-comment-blacklist/master/blacklist.txt) are marked as spam when the customer enters a valid email address ending with @t-online.de.

Example code:

```php
<?php
$input = 'test@t-online.de';
$blacklist = trim( file_get_contents('https://raw.githubusercontent.com/splorp/wordpress-comment-blacklist/master/blacklist.txt') );
foreach(explode("\n", $blacklist) as $blacklist__value) {
    $blacklist__value = trim($blacklist__value);
    $pattern = sprintf('#%s#i', preg_quote($blacklist__value, '#'));
    if(preg_match($pattern, $input)) {
        var_dump($pattern, $blacklist__value, $input);
        die('spam');
    }
}
die('ok');
```

I urgently recommend removing the following 2 lines from blacklist.txt to eliminate these false positives:

```
online.com
online.de
```

**Comment by splorp** [comment]
Hi, David.

Thanks for bringing this to my attention. I’ll remove these two domain-related terms (along with a few more obvious ones that I found) in the next update.

**Comment by splorp** [comment]
This issues has been resolved per commit 22ded9e

**Comment by vielhuber** [comment]
Thanks in advance.

One suggestion: Did you consider adding a test suite for this project which tests on every new release for false positives?

**Comment by splorp** [comment]
It has crossed my mind, but I’ve never set up a test suite … they’re a bit out of my wheelhouse.

I’d appreciate any pointers or information on setting something like that up for this project, if that’s something you’d be interested in helping with.

**Comment by vielhuber** [comment]
> I’d appreciate any pointers or information on setting something like that up for this project, if that’s something you’d be interested in helping with.

Yes, I can contribute by adding a testsuite in one of the following environments

- php (phpunit 8)
- javascript (for example jest)
- bash (shunit2)

Do you have any preference or suggestions on these environments?

Personally I would make the testsuite very simple: just parse two folders consisting of text files containing:

- "false_positive"
- "false_negative"

Then run that testsuite on GitHub Actions (before every merge). 

That would be cool, what do you think?

**Comment by splorp** [comment]
I’m most comfortable with PHP, but bash would work in a pinch.

This sounds like a good plan.

I’ll open this as a new issue, so we can track progress outside of this issue.
