### ISSUE TITLE
Wix site urls getting caught

### ISSUE THREAD

**Issue by luboslives** [splorp/wordpress-comment-blacklist#53]
Hi, just one simple thing I caught this morning.

`anything.wixsite.com` gets caught by the `site.co` filter. Might want to adjust that, as there are a lot of people using Wix and sending their urls.

**Comment by splorp** [comment]
Thanks for the catch. I’ll make this adjustment right away.

**Comment by splorp** [comment]
Keywords relating to this issue have been removed from the block list per commit ffabc58
