### ISSUE TITLE
False positives with period-comma combo

### ISSUE THREAD

**Issue by GaryWLewis** [splorp/wordpress-comment-blacklist#57]
We've had an issue with false positives triggered when visitors enter addresses or abbreviations containing a period followed by a comma: ".,"

Examples triggering the false positive:

"I have an appointment today at 4 p.m., but I need to cancel."

"My address is 123 Maple Dr., Smallville."

Can you please remove ".," from the blacklist since it's too broad? Thanks!

**Comment by splorp** [comment]
Good catch.

This issue has been resolved per commit 26812596fc84f55a08cf58d26473522a1cac59f8
