### ISSUE TITLE
Useful Tools: Sort List of Words and Delete Duplicate Words

### ISSUE THREAD

**Issue by Generosus** [splorp/wordpress-comment-blacklist#59]
Dear Community,

Thought this would help a bit.

- To sort your list of blacklist words, use this tool: [Sort List of Words](https://www.gillmeister-software.com/online-tools/text/sort-list.aspx)
- To delete duplicate words or lines of text, use this tool: [Delete Duplicate Words](https://www.browserling.com/tools/duplicate-lines)

The above tools will help your Blacklist remain lean and mean. 👍

Cheerio!

**Comment by splorp** [comment]
My blacklist is sorted and deduplicated using [BBEdit](http://www.barebones.com/products/bbedit/) prior to each commit.

While the information you posted is certainly useful, it does not apply specifically to this project and should be published elsewhere.

I am closing this issue.

**Comment by Generosus** [comment]
Hi there!

Apologies. You are absolutely correct. Since your list is popular - and many times combined with others - simply wanted to help the community with the above tips. 

No worries. Cheers!

PS: Couldn't find a "label" for the above topic.
