### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by lancedockins** [splorp/wordpress-comment-blacklist#61]
We started receiving reports of high false positivity rates for this anti-spam list recently.  We've run into that a few times when we've used it ourselves.  It's always a bit of a challenge to determine why but we did identify that messages that refer to "your website but" or "your website for" are being blocked.

It's common for end users to say things like "I looked on your website but didn't find it" or if they keep running into issues with blocked messages they'll say something like "I tried your website form" and then they'll be blocked as both of the phrases that I mentioned are in the ban list.

I'm sure that you're right that a lot of spam does use the same list of phrases.  But a few of the phrases I named above may be a bit too overbalanced towards flagging the message as spam than they should be.

Would you consider removing at least the two that I mentioned from your list?

**Comment by splorp** [comment]
> Would you consider removing at least the two that I mentioned from your list?

Thanks for pointing out these false positives, Lance.

I’ll remove the two that you’ve mentioned and take a look for any other similar phrases that could cause a similar issue.

**Comment by splorp** [comment]
This issue has been resolved per commit 883df69
