### ISSUE TITLE
Blacklisted terms too common/broad

### ISSUE THREAD

**Issue by GaryWLewis** [splorp/wordpress-comment-blacklist#62]
The following terms result in too many false positives, especially in industries such as agriculture and manufacturing. (The misspelled versions of these are fine. But these three in particular are just too broad to filter all posts and form submissions.)

equipment manufact
equipment-manufact
nufactur

Additionally, the following term results in a false positive on the word "meridian", which has multiple uses in legitimate posts (a town in Mississippi, the prime meridian, various other scientific and medical fields):

meridia

Thanks for all you do!

**Comment by splorp** [comment]
Hi @GaryWLewis … thanks for letting me know about these relatively common terms.

I will update the blocklist accordingly.

**Comment by splorp** [comment]
This issue has been resolved per commit 7efe765
